# Generated by Django 5.1.7 on 2025-05-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('curator', 'Куратор'), ('admin', 'Администратор')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
